version: '3'
services:
  db:
    ports:
      - "3306:3306"

  backend:
    ports:
      - "8000:8000"

  frontend:
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_REDIRECT_URL=http://localhost:5000

  fuseki:
    ports:
      - "3030:3030"
