"""initial migration

Revision ID: 11915fdc90a2
Revises: 
Create Date: 2025-05-13 18:33:21.278363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11915fdc90a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('issued', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasets',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('issued', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.Column('contact_point', sa.String(length=255), nullable=False),
    sa.Column('access_url_dataset', sa.String(length=255), nullable=True),
    sa.Column('access_url_semantic_model', sa.String(length=255), nullable=True),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('semantic_model_file', sa.LargeBinary(), nullable=True),
    sa.Column('semantic_model_file_name', sa.String(length=255), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('webid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.PrimaryKeyConstraint('identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    op.drop_table('catalogs')
    # ### end Alembic commands ###
