"""initial

Revision ID: 7a055a194917
Revises: a9523031f48a
Create Date: 2024-11-12 16:47:14.436415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '7a055a194917'
down_revision: Union[str, None] = 'a9523031f48a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Prüfen, ob die Tabelle existiert
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)

    if 'datasets' not in inspector.get_table_names():
        op.create_table(
            'datasets',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('description', sa.String(length=1024), nullable=True),
            sa.Column('creation_date', sa.DateTime(), nullable=False),
            sa.Column('last_modified_date', sa.DateTime(), nullable=False),
            sa.Column('incremental_replace', sa.String(length=50), nullable=False),
            sa.Column('owner_id', sa.Integer(), nullable=False),
            sa.Column('contact_id', sa.Integer(), nullable=False),
            sa.Column('is_public', sa.Boolean(), nullable=False),
            sa.Column('file_path', sa.String(length=1024), nullable=True),
            sa.Column('file_blob', sa.LargeBinary(), nullable=True),
            sa.ForeignKeyConstraint(['contact_id'], ['persons.id']),
            sa.ForeignKeyConstraint(['owner_id'], ['persons.id']),
            sa.PrimaryKeyConstraint('id')
        )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasets')
    # ### end Alembic commands ###
