"""Remove dataspaces and pods table

Revision ID: 99539428add7
Revises: f037dd9de5b6
Create Date: 2025-04-01 12:59:06.279710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '99539428add7'
down_revision: Union[str, None] = 'f037dd9de5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Optional: Entferne zuerst die Foreign Key Constraint (wenn du den Namen kennst)
    op.drop_constraint('fk_datasets_dataspace_id', 'datasets', type_='foreignkey')  # Name anpassen!

    # 2. Dann Spalte entfernen, falls noch da:
    op.drop_column('datasets', 'dataspace_id')  # optional, falls du sie eh loswerden willst

    # 3. Dann Tabelle löschen
    op.drop_table('dataspaces')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataspaces',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('link', mysql.VARCHAR(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
