"""Replace publisher_id and contact_point_id with string fields

Revision ID: a7a38ff54842
Revises: dbbf4833bcc4
Create Date: 2025-04-01 14:11:16.476029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a7a38ff54842'
down_revision: Union[str, None] = 'dbbf4833bcc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('publisher', sa.String(length=255), nullable=False))
    op.add_column('datasets', sa.Column('contact_point', sa.String(length=255), nullable=False))
    op.drop_constraint('datasets_ibfk_1', 'datasets', type_='foreignkey')
    op.drop_constraint('datasets_ibfk_2', 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'publisher_id')
    op.drop_column('datasets', 'contact_point_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('contact_point_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('datasets', sa.Column('publisher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('datasets_ibfk_2', 'datasets', 'agents', ['contact_point_id'], ['id'])
    op.create_foreign_key('datasets_ibfk_1', 'datasets', 'agents', ['publisher_id'], ['id'])
    op.drop_column('datasets', 'contact_point')
    op.drop_column('datasets', 'publisher')
    # ### end Alembic commands ###
