"""Use identifier as primary key

Revision ID: dbbf4833bcc4
Revises: 99539428add7
Create Date: 2025-04-01 13:21:23.163962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dbbf4833bcc4'
down_revision: Union[str, None] = '99539428add7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('identifier', table_name='datasets')
    op.drop_column('datasets', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
    op.create_index('identifier', 'datasets', ['identifier'], unique=True)
    # ### end Alembic commands ###
