"""Rename access_url and download_url fields

Revision ID: f037dd9de5b6
Revises: a917338116ca
Create Date: 2025-03-27 14:29:42.699043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f037dd9de5b6'
down_revision: Union[str, None] = 'a917338116ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('access_url_dataset', sa.String(length=255), nullable=True))
    op.add_column('datasets', sa.Column('access_url_semantic_model', sa.String(length=255), nullable=True))
    op.drop_column('datasets', 'download_url')
    op.drop_column('datasets', 'access_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('access_url', mysql.VARCHAR(length=1024), nullable=True))
    op.add_column('datasets', sa.Column('download_url', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_column('datasets', 'access_url_semantic_model')
    op.drop_column('datasets', 'access_url_dataset')
    # ### end Alembic commands ###
